<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "news_ttnewsimport"
 *
 * Auto generated by Extension Builder 2013-11-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'tt_news importer',
	'description' => 'Importer of ext:tt_news items to ext:news',
	'category' => 'be',
	'author' => 'Frans Saris',
	'author_email' => 'frans@beech.it',
	'company' => 'Beech.it',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
			'php' => '5.3.0-0.0.0',
			'news' => '2.999.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);